service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  environment:
    PRODUCTS_TABLE_NAME: products
    STOCKS_TABLE_NAME: stocks
    SNS_TOPIC_ARN: 
      Ref: "CreateProductTopic"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE_NAME}"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE_NAME}/index/*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STOCKS_TABLE_NAME}"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STOCKS_TABLE_NAME}/index/*"
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            Fn::GetAtt: [ CatalogItemsQueue, Arn ]
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            Ref: CreateProductTopic
  httpApi:
    cors: true

functions:
  getProductsList:
    handler: getProductsList.handler
    events:
      - httpApi:
          method: GET
          path: /products
  createProduct:
    handler: createProduct.handler
    events:
      - httpApi:
          method: POST
          path: /products
  getProductsById:
    handler: getProductsById.handler
    events:
      - httpApi:
          method: GET
          path: /products/{productId}
  catalogBatchProcess:
    handler: catalogBatchProcess.handler
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn

resources:
  Resources:
    CatalogItemsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: catalogItemsQueue
    CreateProductTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: createProductTopic
    EmailSubscriptionForCreateProductTopic:
      Type: "AWS::SNS::Subscription"
      Properties:
          Endpoint: cilgaiscan@gmail.com
          Protocol: email
          TopicArn: {"Ref": "CreateProductTopic"}
