service: authorization-service
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  basicAuthorizer:
    handler: basicAuthorizer.handler
