service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  environment:
    IMPORT_BUCKET_NAME: shop-aws-import
    QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/962081227256/catalogItemsQueue"
    REGION_NAME: eu-central-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::shop-aws-import"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::shop-aws-import/*"
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource: "arn:aws:sqs:eu-central-1:962081227256:catalogItemsQueue"
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        name: basicAuthorizer
        functionArn: "arn:aws:lambda:eu-central-1:962081227256:function:authorization-service-dev-basicAuthorizer"
        type: request
        enableSimpleResponses: true
        payloadVersion: "2.0"

functions:
  importProductsFile:
    handler: importProductsFile.handler
    events:
      - httpApi:
          method: GET
          path: /import
          authorizer:
            name: basicAuthorizer
  importFileParser:
    handler: importFileParser.handler
    events:
      - s3:
          bucket: "${self:provider.environment.IMPORT_BUCKET_NAME}"
          event: "s3:ObjectCreated:*"
          rules:
            - prefix: "uploaded/"
          existing: true
